title: "Lino Grubben"
description: "I'm a designer and entrepreneur writing about product, design, and what else is on my mind."
baseurl: ""
url: "https://linogrubben.com"
permalink: /:title/
plugins:
  - jekyll-feed